INPUT_SCHEMA = {
    "prompt": {
        "type": str,
        "required": True,
    },
    "temperature": {"type": float, "required": False, "default": 0.9},
    "top_k": {"type": int, "required": False, "default": 40},
    "top_p": {"type": float, "required": False, "default": 0.9},
    "min_p": {"type": float, "required": False, "default": 0},
    "tfs": {"type": float, "required": False, "default": 0},
    "typical": {"type": float, "required": False, "default": 0},
    "max_new_tokens": {"type": int, "required": False, "default": 40},
    "token_repetition_penalty": {"type": float, "required": False, "default": 1.15},
    "token_repetition_range": {"type": int, "required": False, "default": -1},
    "token_repetition_decay": {"type": int, "required": False, "default": 0},
    "mirostat": {"type": bool, "required": False, "default": False},
    "mirostat_tau": {"type": float, "required": False, "default": 1.5},
    "mirostat_eta": {"type": float, "required": False, "default": 0.1},
    "stop": {"type": list, "required": False, "default": []},
}
